<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.4" tiledversion="1.4.3" name="tamra-tileset" tilewidth="8" tileheight="8" tilecount="30" columns="6">
    <image source="new-tileset.png" trans="ff00ff" width="48" height="40" />
    <tile
      id="0"
      type="3"
    />
    <tile
      id="1"
      type="1"
    />
    <tile
      id="2"
      type="1"
    />
    <tile
      id="6"
      type="2"
    />
    <tile
      id="7"
      type="1"
    />
    <tile
      id="8"
      type="1"
    />
    <tile
      id="12"
      type="2"
    />
    <tile
      id="13"
      type="1"
    />
    <tile
      id="14"
      type="2"
    />
    <tile
      id="18"
      type="1"
    />
    <tile
      id="19"
      type="1"
    />
    <tile
      id="20"
      type="1"
    />
    <tile
      id="24"
      type="2"
    />
    <tile
      id="25"
      type="1"
      probability="0"
    />
    <tile
      id="26"
      type="2"
    />
</tileset>
